runtime: nodejs12
instance_class: F1
inbound_services:
  - warmup
automatic_scaling:
  min_instances: 1
  min_idle_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.8
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
